CREATE DATABASE QLBH_
USE QLBH_
--DROP DATABASE QLBH_

CREATE TABLE KHACHHANG (
	MAKH varchar(50) primary key,
	HOTEN nvarchar(50) NOT NULL,
	GIOITINH nvarchar(5),
	DCHI nvarchar(50),
	SDT varchar(50) NOT NULL
)

CREATE TABLE NGUOIDUNG (
	MAND varchar(50) primary key,
	TENND nvarchar(50) NOT NULL ,
	NGSINH smalldatetime,
	GIOITINH nvarchar(5),
	SDT char(50) NOT NULL ,
	DIACHI nvarchar(50),
	USERNAME char(50),
	PASS nvarchar(max),
	QTV bit NOT NULL DEFAULT (0),
	TTND bit NOT NULL DEFAULT(1),
	AVA varchar(max),
	MAIL varchar(100)
)

CREATE TABLE SANPHAM (
	MASP varchar(50) primary key,
	TENSP nvarchar(50) NOT NULL,
	GIA int NOT NULL,
	MOTA nvarchar(max),
	HINHSP nvarchar(max),
	SL int NOT NULL,
	LOAISP nvarchar(50),
	SIZE nvarchar(50)
)

CREATE TABLE HOADON (
	SOHD int primary key,
	MAND varchar(50),
	MAKH varchar(50),
	NGHD smalldatetime NOT NULL,
	TRIGIA int  NOT NULL,
	KHUYENMAI int	
)

CREATE TABLE PHIEUNHAP (
	MAPN int primary key,
	MAND varchar(50),
	NGAYNHAP smalldatetime NOT NULL 
)

CREATE TABLE CTHD (
	SOHD int,
	MASP varchar(50),
	SL int NOT NULL,
	primary key(SOHD, MASP)
)

CREATE TABLE CTPN (
	MAPN int,
	MASP varchar(50),
	SL int NOT NULL,
	primary key(MAPN, MASP)
)

ALTER TABLE HOADON
ADD CONSTRAINT FK_KH_HD
FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_ND
FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CT_HD
FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CT_SP
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CTPN 
ADD CONSTRAINT FK_CN_SP
FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

ALTER TABLE CTPN
ADD CONSTRAINT FK_CN_PN
FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN)

ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_ND
FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)
GO

INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH01',N'Nguyễn Văn A',N'731 Trần Hưng Đạo, Q5, TPHCM','0908823451',N'Nam')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH02',N'Trần Thị B',N'23/5 Nguyễn Trãi, Q5, TPHCM','0908256478',N'Nữ')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH03',N'Trần Văn C',N'45 Nguyễn Du, Q1, TPHCM','0938776266',N'Nam')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH04',N'Trần D',N'50/34 Lê Đại Hành, Q10, TPHCM','0917325476',N'Nam')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH05',N'Lê Thị E',N'34 Trương Định, Q3, TPHCM','0908246108',N'Nữ')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH06',N'Nguyễn Văn F',N'227 Nguyễn Văn Cừ, Q5, TPHCM','0908631738',N'Nam')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH07',N'Nguyễn Văn G',N'32/3 Trần Bình Trọng, Q5, TPHCM','0916783565',N'Nam')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH08',N'Phan Thị H',N'45/2 An Dương Vương, Q5, TPHCM','0938435756',N'Nữ')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH09',N'Đào Thị I',N'873 Lê Hồng Phong, Q5, TPHCM','0908654763',N'Nữ')
INSERT INTO KHACHHANG(MAKH,HOTEN,DCHI, SDT,GIOITINH) VALUES('KH10',N'Lê K',N'34/34B Nguyễn Trãi, Q1, TPHCM','0908768904',N'Nam')